name: CI Build and Test (Python)

on:
  push:
    branches: [ "main" , "develop" , "realase"] 
  pull_request:
    branches: [ "main" , "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Configuração do Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 2. Instalação das dependências e Pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt 

    # 3. EXECUÇÃO DOS TESTES TDD (CRUCIAL PARA O PROJETO)
    - name: Run tests
      run: |
        pytest
